### ISSUE TITLE
glog adding log files for each execution

### ISSUE THREAD

**Issue by jkerry** [jkerry/nagios-foundation#33]
It appears that the glog library is creating a log file for every execution in the $env:TEMP directory for the executing user.  This can get real bad real fast.  We should switch to a logging library that logs to STDOUT / STDERR directly as a default or set default glog parameters to log to STDERR/STDOUT

**Comment by quaggoth** [comment]
The `glog` library uses the flag `-logtostderr` to prevent output from going to files. Setting it to `true` is what is needed. Setting it in code with `flag.Set("logtostderr", "true")` before calling `flag.Parse()` prevents the write-to-file behavior.

If we decide to use this, perhaps now is the time to have a central *bootstrap* type package or function that is commonly called at the top of our `main` packages. We could also use that for the version output functionality I presented earlier.

Let's determine what we'd like to do and I can write up some sample code with a PR.

**Comment by quaggoth** [comment]
A shortcoming of simply using `flag.Set("logtostderr", "true")` is the user is no longer able to override `logtostderr` from the command line. After reading about the `flag` package in detail along with writing a lot of experimental code I was able to write the following function which will leave the flag untouched if specified by the user on the command line or force it to `true` if not specified. A little more work made it more generic and reusable and for our use case can be called with `SetFlagIfNotProvided("logtostderr", "true")`. We should decide if we'll stick with `glog` for now and if so, how to place this in a central location.

```golang
// Sets a command line flag if it wasn't provided. This
// overcomes a command line flag in library being set
// to a different default value than desired.
//
// Returns true if the command line flag was not provided
// and therefore was set to the value provided.
func SetFlagIfNotProvided(flagName string, flagValue string) bool {
	flagSet := false
	flag.Parse()

	flag.Visit(func(f *flag.Flag) {
		if (*f).Name == flagName {
			flagSet = true
		}
	})

	if !flagSet {
		flag.Set(flagName, flagValue)
	}

	return !flagSet
}
```
