### ISSUE TITLE
Use V function for glog

### ISSUE THREAD

**Issue by quaggoth** [jkerry/nagios-foundation#61]
With the PRs #36 and #46, `glog` is now sending output to `stderr` which is getting mixed in with normal command output. This is especially affecting any use of the `perfcounters` package and when emitting errors, the `memory` package.

`glog` offers something called `v-style logging` and `V functions` which can be used to wrap these calls to prevent this output when the commands are deployed to production, yet they can be enabled when in test or development type environments. Implement this.

**Comment by jkerry** [comment]
Assuming this is closed. re-open if it doesn't fix the problem @quaggoth
